### PR TITLE
Add utilities for parsing trees

### PR DESCRIPTION
**Pull request by pawel-czyz**
Hi Laurenz,

These are the utilities for parsing the trees from CSV, which are compatible with the data format developed by Xiang. We used them in the [PhIRL project](https://github.com/cbg-ethz/phirl) and the scripts there in theory could serve as an example how to use these methods. However, if the API is not clear, please let me know – I'd like the documentation here to be complete enough.

### CODE REVIEW

**Review by laurenzkeller — COMMENTED** [review]
Hi Pawel,
I don't understand exactly why we would parse a data frame into a tree. If we want to compare the frequency of tree sizes and mutations of R and Python, wouldn't it be better to just create CSV files that contain the information of trees?
Best regards,
Laurenz

**Comment by pawel-czyz** [comment]
This is a fair point! :slightly_smiling_face:  

The idea is that we have two data sets of trees:
$$t_1, \dotsc, t_N$$
and
$$T_1, \dotsc, T_N$$
and we would like to check whether they are likely to come from the same distribution. As trees are hard to compare, we instead look at summary statistic, i.e., some function from the tree space $\mathcal T$ to some Euclidean space $\mathbb R^k$, and compare $\{s_(t_i)\}$ with $\{s(T_i)\}$.

Hence, the focus is on the tree and a function of the signature $\mathcal T\to \mathbb R^k$. In particular, there may exist summary statistics which are hard to calculate from a CSV as they use the tree structure. For example, the tree depth.

Another reason are (prior and posterior) predictive checks we will use to develop the models, which will also use functions of the same signature.
More on this topic [here](https://mc-stan.org/docs/2_28/stan-users-guide/ppcs.html) and in [BDA](http://www.stat.columbia.edu/~gelman/book/), which I'd recommend downloading.

**Review by laurenzkeller — APPROVED** [review]
Ok. So we need to write the R trees to a CSV file first and then create Python trees using the CSV file and afterwards we can do the comparison by looking at a summary statistic?

**Comment by pawel-czyz** [comment]
> Ok. So we need to write the R trees to a CSV file first and then create Python trees using the CSV file and afterwards we can do the comparison by looking at a summary statistic?

Yes, exactly – then we have Python-generated trees and R-generated trees in Python :slightly_smiling_face:

**Pull request merged**
